package com.nowcoder.seckill.dao;

import com.nowcoder.seckill.entity.ItemStock;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface ItemStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Tue Jan 19 14:37:36 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Tue Jan 19 14:37:36 CST 2021
     */
    int insert(ItemStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Tue Jan 19 14:37:36 CST 2021
     */
    ItemStock selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Tue Jan 19 14:37:36 CST 2021
     */
    List<ItemStock> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Tue Jan 19 14:37:36 CST 2021
     */
    int updateByPrimaryKey(ItemStock record);

    /**
     * 根据商品ID查询库存信息
     *
     * @param itemId
     * @return
     */
    ItemStock selectByItemId(Integer itemId);

    /**
     * 扣减库存
     *
     * @param itemId
     * @param amount
     * @return
     */
    int decreaseStock(Integer itemId, Integer amount);
}